import random
import hashlib

intro: str ='This program  is a much simplified model of  2010 Sony Playstation 3 cryptographic vulnerability.\n'
print(intro)
# Proudly Engineered by Zachary Roberts 22 JUN 2026.
# VVV Very roughly how Sony intended to secure the system. VVV
# declarations 

PRIVATE_KEY: int = 6 # Only Sony knew this constant value.

# SIMULATE USER MAKING REQUESTS TO PS3 SYSTEM
secure_boot_raw_string = 'secure boot' 
boot_loader_raw_string = 'boot loader'

# SIMPLIFIED PS3 HASHING REQUEST OPERATION

# encode string into bytes, convert to SHA-1 object, (PS3 used SHA-1 hashing)
secure_boot_obj = hashlib.sha1(secure_boot_raw_string.encode())
boot_loader_obj = hashlib.sha1(boot_loader_raw_string.encode())

# convert SHA-1 objs to hexadecimal strings
secure_boot_hex: str = secure_boot_obj.hexdigest()
boot_loader_hex: str = boot_loader_obj.hexdigest()

# convert hex string into int to use in valid_signature_1 and valid_signature_2 expression

secure_boot_request: int = int(secure_boot_hex, 16) 
boot_loader_request: int = int(boot_loader_hex, 16)

# floor division at end to make output manageable, 2 line makes code more legible
secure_boot_request: int = secure_boot_request // 10 ** 46
boot_loader_request: int = boot_loader_request // 10 ** 46

# SIMULATED PS3 NONCE GENERATION

preamble: str = '''
Sony needed multiple signatures to validate requests. In this program these are:
 
valid_signature_1 and valid_signature_2 are complete validated requests. 
The PS3 boot order checks if these are valid to function as expected

valid_requests are comprised of simulated ECDSA operations Where:


signature_r(comprised of a constant value of nonce, a cybersecurity vulnerability),
PRIVATE_KEY known only to Sony,
the hashed request,
and secure_boot_request or boot_loader_request

are added together, than divided by nonce. 

the simulated validation request equation is:

valid_signature1 = (signature_r + PRIVATE_KEY + secure_boot_request) / nonce

I seeded random with 4 to ensure that nonce and signature_r are constants to simulate the mistake Sony made.

Below if the system boots as expected it will return "Sony Computer Entertainment Playstation 3" 
\n'''

print(preamble)

random.seed(4) # Sony's mistake. 
nonce: int = random.randint(1, 11) # generated by ECDSA
signature_r: int = nonce * 5
# flaw in signatures resulted in using a constant for nonce and signature_r.
# once known the rest of the PRIVATE_KEY and nonce can be deduced.
 
# confirms operation request is valid
valid_signature_1: float = float(signature_r + PRIVATE_KEY + secure_boot_request) / nonce
# confirms operation request is valid
valid_signature_2: float = float(signature_r + PRIVATE_KEY + boot_loader_request) / nonce

# SIMULATED FAILED VALIDATION
# uncomment to test
#secure_boot_request = PRIVATE_KEY + 3

# PRINT CHECKS TO BUILD PROGRAM
#print(secure_boot_request)
#2print(boot_loader_request)
#print(PRIVATE_KEY)
#print(f'nonce is: {nonce}')

# simulate boot chain of trust, if chain broken do not boot. 
if (valid_signature_1 == float(signature_r + PRIVATE_KEY + secure_boot_request) / nonce 
   and valid_signature_2 == float(signature_r + PRIVATE_KEY + boot_loader_request) / nonce
):
    print('Sony Computer Entertainment Playstation 3\n')
else:
    print('The system software cannot run correctly. Press PS button to try to restart the system.\n')

# Simplified version of how Fail0verflow deduced the PRIVATE_KEY once nonce was a known value.

print('How FailOverflow deduced PRIVATE_KEY and nonce.\n')

print(f'''Through metadata, hackers knew that:
      valid_signature_1 is: {valid_signature_1}, 
      valid_signature_2 is: {valid_signature_2},
      signature_r is: {signature_r},
      secure_boot_request is: {secure_boot_request},
      boot_loader_request is: {boot_loader_request}
      \n''')


# Fail0verflow reconstructs Sony signatures from public data
user_string: str ='''
Fail0verflow reconstructs Sony signatures from public data.
The PRIVATE_KEY and nonce are unknown to the hackers at this time.\n'''

hacked_valid_signature_1 = (20 + PRIVATE_KEY + 77) / nonce

hacked_valid_signature_2 = (20 + PRIVATE_KEY + 98) / nonce

print(user_string)

# GET nonce
# recover the nonce by solving the signature equations.
# hacked_nonce = (98 - 77) / (31.0 - 25.75)
user_string1: str = '''
Next Fail0verflow needed to get the nonce.
They recovered it by solving the signature equations.
hacked_nonce = (98 - 77) / (31.0 - 25.75)\n'''

print(user_string1)
hacked_nonce = int((boot_loader_request - secure_boot_request) / (hacked_valid_signature_2 - hacked_valid_signature_1))
print(f'hacked_nonce is: {hacked_nonce}\n')

# GET PRIVATE_KEY
#Substitute hacked_nonce (4) into one of the signature equations 
#hacked_private_key = (25.75 * hacked_nonce) - 20 - 77
user_string2: str ='''
Lastly, Fail0verflow needed to get the secure Sony PRIVATE_KEY,
They substituted the hacked_nonce (4) into once of the signature equations
hacked_private_key = (25.75 * hacked_nonce) -20 - 77\n'''

print(user_string2)
hacked_private_key = int((hacked_valid_signature_1 * hacked_nonce) - signature_r - secure_boot_request)

print(f'hacked_private_key is: {hacked_private_key}\n')

print("Now let's try to boot the system with hacked values, will return 'Sony Computer Entertainment Playstation 3' if successful.\n")

# simulate boot chain of trust, if chain broken do not boot. 
if (hacked_valid_signature_1 == float(signature_r + hacked_private_key + secure_boot_request) / hacked_nonce 
   and valid_signature_2 == float(signature_r + hacked_private_key + boot_loader_request) / hacked_nonce
):
    print('Sony Computer Entertainment Playstation 3\n')
else:
    print('The system software cannot run correctly. Press PS button to try to restart the system.\n')