import random
import hashlib

'''
This program simplifies the 2010 Sony Playstation 3 cryptographic failure.

22 JUN 2026, Proudly Engineered by Zachary Roberts

'''
# VVV Roughly how Sony intended to secure the system. VVV
# declarations 

PRIVATE_KEY: float = 6.0 # Only Sony knew this value. It was a constant, this was the cybersecurity oversight.

# SIMULATE USER MAKING REQUESTS TO PS3 SYSTEM
secure_boot_raw_string = 'secure boot' 
boot_loader_raw_string = 'boot loader'

# SIMPLIFIED PS3 HASHING REQUEST OPERATION

# encode string into bytes, convert to SHA-1 object, (PS3 used SHA-1 hashing)
secure_boot_obj = hashlib.sha1(secure_boot_raw_string.encode())
boot_loader_obj = hashlib.sha1(boot_loader_raw_string.encode())

# convert SHA-1 objs to hexadecimal strings
secure_boot_hex: str = secure_boot_obj.hexdigest()
boot_loader_hex: str = boot_loader_obj.hexdigest()

# convert hex string into int to use in signature_1 and signature_2 expression
secure_boot_request: int = int(secure_boot_hex, 16)
boot_loader_request: int = int(boot_loader_hex, 16)



# SIMULATED PS3 NONCE GENERATION
nonce: float = random.random() # generated by ECDSA
# flaw in signatures resulted in using a constant for the private key, once knowN the rest of the signature can be deduced. 
signature_1: float = float(PRIVATE_KEY + secure_boot_request) / nonce # confirms operation request is valid
signature_2: float = float(PRIVATE_KEY + boot_loader_request) / nonce # confirms operation request is valid

# SIMULATED FAILED VALIDATION
secure_boot_request = PRIVATE_KEY + 3

# PRINT CHECKS TO BUILD PROGRAM
#print(secure_boot_request)
#print(boot_loader_request)
#print(PRIVATE_KEY)
#print(f'nonce is: {nonce}')
#print(f'signature_1 is: {signature_1}')
#print(f'signature_2 is: {signature_2}')

# simulate boot chain of trust, if chain broken do not boot. 
if signature_1 == (PRIVATE_KEY + secure_boot_request) / nonce and signature_2 == (PRIVATE_KEY + boot_loader_request) / nonce:
    print('Sony Computer Entertainment Playstation3')
else:
    print('The system software cannot run correctly. Press PS button to try to restart the system.')

