import random
'''
This program simplifies the 2010 Sony Playstation 3 cryptographic failure.

22 JUN 2026, Proudly Engineered by Zachary Roberts

'''
# declarations 

PRIVATE_KEY: float = 6.0 # Only Sony knew this value, it was a constant, this was the cybersecurity oversight.
boot_loader_request: float = 2.0 # example of user operation, this value would be hashed
secure_boot_request: float = 4.0 # example of user operation, this value would be hashed
nonce: float = random.random() # generated by ECDSA
signature_1: float = (PRIVATE_KEY + secure_boot_request) / nonce # confirms operation request is valid
signature_2: float = (PRIVATE_KEY + boot_loader_request) / nonce # confirms operation request is valid


print(PRIVATE_KEY)
print(f'nonce is: {nonce}')
print(f'signature_1 is: {signature_1}')
print(f'signature_2 is: {signature_2}')

# simulate boot chain of trust, if chain broken do not boot. 
if signature_1 == (PRIVATE_KEY + secure_boot_request) / nonce and signature_2 == (PRIVATE_KEY + boot_loader_request) / nonce:
    print('Sony Computer Entertainment Playstation3')
else:
    print('The system software cannot run correctly. Press PS button to try to restart the system.')

